name: CI Workflow

on:
    # Trigger för manuella körningar
    workflow_dispatch:
    # Trigger för push till main och testning-grenarna
    # push:
    #     branches:
    #         - main
    #         - test
    # # Trigger för pull requests mot main
    # pull_request:
    #     branches:
    #         - main

jobs:
    build-and-test:
        runs-on: ubuntu-latest

        steps:
            # Steg 1: Hämta koden
            - name: Checkout code
              uses: actions/checkout@v4

            # Steg 2: Sätt upp Node.js med caching
            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 18
                  cache: 'npm' # Hanterar caching av Node.js-moduler automatiskt

            # Steg 3: Installera beroenden med npm ci
            - name: Install dependencies
              run: npm ci

            # Steg 4: Bygga projektet (om build-script finns)
            - name: Build project
              run: npm run build --if-present

            # Steg 5: Köra tester
            - name: Run tests
              run: npm test
